// Firebase configuration for this app, generated by hand from the values in
// android/app/google-services.json (Firebase console > project settings).
//
// Mirrors the file that `flutterfire configure` would generate. Only Android
// is configured; add other platforms in the Firebase console first if needed.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'register a web app in the Firebase console first.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform - '
          'only Android is configured in the Firebase console.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDr5soDcLV4YvxWH0Kxfh8m53MLqwetR2Q',
    appId: '1:217708551159:android:81cb7688e1398c77ccacf2',
    messagingSenderId: '217708551159',
    projectId: 'alarm-clock-app-d44ed',
    storageBucket: 'alarm-clock-app-d44ed.firebasestorage.app',
  );
}
